#!/bin/bash

echo "🔍 VERIFICAÇÃO: Configuração OAuth"
echo "=================================="

echo "📱 Configurações do App:"
echo "Package Name: com.garageminteligente.app"
echo "SHA-1: BE:D0:65:23:C4:A4:B4:03:A7:1C:4A:C9:F7:BC:59:DF:CF:74:01:F8"
echo "SHA-256: 7F:CF:50:F0:BF:0F:C4:24:EB:99:1A:76:F5:97:4D:00:27:4B:74:D2:AE:A0:E4:D5:40:C5:A6:01:98:46:4F:08"
echo ""

echo "🔧 VERIFICAÇÕES NECESSÁRIAS:"
echo ""
echo "1. 📋 OAuth Consent Screen:"
echo "   URL: https://console.cloud.google.com/apis/credentials/consent?project=autocare-platform"
echo "   ✅ Verificar se está configurado"
echo "   ✅ User Type: External"
echo "   ✅ App name: Garagem Inteligente"
echo "   ✅ User support email: configurado"
echo "   ✅ Scopes: ../auth/userinfo.email e ../auth/userinfo.profile"
echo ""

echo "2. 🔑 OAuth Client ID:"
echo "   URL: https://console.cloud.google.com/apis/credentials?project=autocare-platform"
echo "   ✅ Verificar se existe OAuth Client para Android"
echo "   ✅ Package name: com.garageminteligente.app"
echo "   ✅ SHA-1: BE:D0:65:23:C4:A4:B4:03:A7:1C:4A:C9:F7:BC:59:DF:CF:74:01:F8"
echo ""

echo "3. 🔥 Firebase Authentication:"
echo "   URL: https://console.firebase.google.com/project/autocare-platform/authentication/providers"
echo "   ✅ Google Sign-In habilitado"
echo "   ✅ Project support email configurado"
echo ""

echo "4. 📚 APIs Habilitadas:"
echo "   URL: https://console.cloud.google.com/apis/library?project=autocare-platform"
echo "   ✅ Google+ API (se disponível)"
echo "   ✅ Google Sign-In API"
echo "   ✅ Firebase Authentication API"
echo ""

echo "🚨 ERRO 'Missing or Insufficient Permission':"
echo "============================================="
echo "Este erro indica problema com permissões OAuth."
echo ""
echo "🔧 SOLUÇÕES:"
echo "1. Configure o OAuth Consent Screen"
echo "2. Verifique se o OAuth Client ID está correto"
echo "3. Adicione seu email como test user"
echo "4. Verifique se as APIs estão habilitadas"
echo ""
echo "📱 Para testar após correção:"
echo "./fix-google-signin.sh"
